### ISSUE TITLE
Can it be used in an application ?

### ISSUE THREAD

**Issue by ritesh-malav** [SteGriff/pokemon-badges#1]
Will there be licence issue for these images if I use these images in my personal application ?

**Comment by SteGriff** [comment]
Hi Ritesh, that's fine! Please go ahead and use them. The license I chose for these badges is http://creativecommons.org/licenses/by/3.0/ so please mention me or the original repository in the credits of your app somewhere :) I'd love to see your application when it's finished.

**Comment by ritesh-malav** [comment]
ThankU. It's already live on play store : https://play.google.com/store/apps/details?id=com.mathcharger Do have a look. It is still in alpha phase and I don't have many users but I am planning to introduce badges for users on their achievements.

**Comment by ritesh-malav** [comment]
Hi @SteGriff would it be possible for you to share theme images in png format with me ? I need all these images separately. You can mail them to me at ritesh.malav86@gmail.com

**Comment by SteGriff** [comment]
Hi Ritesh. No, sorry I won't do that. 

This art is provided for free, and I'm not inclined to do any work for your particular use case. You have two options: Cut up the provided PNG file using a graphics tool, or even the Windows Snip tool (https://github.com/SteGriff/pokemon-badges/blob/master/badges.png) or export the individual artworks from the source SVGs (https://github.com/SteGriff/pokemon-badges/tree/master/svg) using Inkscape.

The sources are provided specifically so you can do these things yourself :) All the best!

**Comment by ritesh-malav** [comment]
> Hi Ritesh. No, sorry I won't do that.
> 
> This art is provided for free, and I'm not inclined to do any work for your particular use case. You have two options: Cut up the provided PNG file using a graphics tool, or even the Windows Snip tool (https://github.com/SteGriff/pokemon-badges/blob/master/badges.png) or export the individual artworks from the source SVGs (https://github.com/SteGriff/pokemon-badges/tree/master/svg) using Inkscape.
> 
> The sources are provided specifically so you can do these things yourself :) All the best!

Yes @SteGriff I am doing that only. The reason why I asked for this is because maybe you would have had these images separately and then combined them. But no worries, I will make individual images out of it.
